# Generated by Django 5.1.1 on 2024-11-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politico',
            fields=[
                ('CPF', models.IntegerField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('Partido_atual', models.CharField(max_length=31)),
                ('Estado', models.CharField(max_length=15)),
                ('Estado_nascimento', models.CharField(max_length=15)),
                ('Municipio_nascimento', models.CharField(max_length=15)),
                ('Data_nascimento', models.DateField()),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=15)),
                ('Escolaridade', models.CharField(max_length=255)),
                ('Profissao', models.CharField(max_length=255)),
                ('Telefone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('ID_camara_politico', models.IntegerField()),
                ('Foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
