# Generated by Django 5.1.1 on 2024-11-07 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politico',
            name='Telefone',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message="O telefone deve ser do seguinte formato: '1234-5678'.", regex='^\\d{4}-\\d{4}$')]),
        ),
    ]
