# Generated by Django 5.1.1 on 2024-11-07 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0002_alter_politico_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('Sigla_Orgao', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('Sala', models.CharField(max_length=255)),
                ('ID_Camara_Orgao', models.IntegerField()),
                ('Data_Inicio', models.DateField()),
                ('Data_Fim', models.DateField()),
                ('Website', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='politico',
            old_name='Data_nascimento',
            new_name='Data_Nascimento',
        ),
        migrations.RenameField(
            model_name='politico',
            old_name='Estado_nascimento',
            new_name='Estado_Nascimento',
        ),
        migrations.RenameField(
            model_name='politico',
            old_name='ID_camara_politico',
            new_name='ID_Camara_Politico',
        ),
        migrations.RenameField(
            model_name='politico',
            old_name='Municipio_nascimento',
            new_name='Municipio_Nascimento',
        ),
        migrations.RenameField(
            model_name='politico',
            old_name='Partido_atual',
            new_name='Partido_Atual',
        ),
        migrations.AlterField(
            model_name='politico',
            name='CPF',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="O CPF deve ser do seguinte formato: '12345678912'.", regex='^\\d{11}$')]),
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('Codigo_Despesa', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Tipo_Despesa', models.CharField(max_length=255)),
                ('PDF_Documento', models.FileField(upload_to='')),
                ('Valor_Atual', models.IntegerField()),
                ('Fornecedor', models.CharField(max_length=255)),
                ('Data', models.DateField()),
                ('CNPJ_Fornecedor', models.CharField(max_length=255)),
                ('CPF_Politico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico')),
            ],
        ),
        migrations.CreateModel(
            name='Frente',
            fields=[
                ('ID_Camara_Frente', models.IntegerField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('PDF_Frente', models.FileField(upload_to='')),
                ('CPF_Coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante_Frente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Camara_Frente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.frente')),
                ('Politico_CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante_Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Politico_CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico')),
                ('Sigla_Orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.orgao')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('Sigla_Partido', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('Numero_Eleitoral', models.IntegerField()),
                ('Qty_Membros_Camara', models.IntegerField()),
                ('ID_Camara_Partido', models.IntegerField()),
                ('Lider_Partido_CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico')),
            ],
        ),
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo', models.CharField(max_length=255)),
                ('Politico_CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico')),
                ('Sigla_Partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante_Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo', models.CharField(max_length=255)),
                ('Politico_CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico')),
                ('Sigla_Partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('ID_Camara_Proposicao', models.IntegerField(primary_key=True, serialize=False)),
                ('Numero', models.CharField(max_length=255)),
                ('Ementa', models.FileField(upload_to='')),
                ('Ano_Proposicao', models.CharField(max_length=255)),
                ('Situacao', models.CharField(max_length=255)),
                ('Data_Situacao', models.CharField(max_length=255)),
                ('Keywords', models.CharField(max_length=255)),
                ('Tipo', models.CharField(max_length=255)),
                ('Sigla_Orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.orgao')),
            ],
        ),
        migrations.CreateModel(
            name='Autor_Proposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Politico_CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico')),
                ('ID_Camara_Proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.proposicao')),
            ],
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('ID_Camara_Votacao', models.IntegerField(primary_key=True, serialize=False)),
                ('Qty_Votos', models.IntegerField()),
                ('Resultado', models.CharField(max_length=255)),
                ('Data', models.DateField()),
                ('Sigla_Orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.orgao')),
            ],
        ),
        migrations.CreateModel(
            name='Votacao_Politico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voto', models.CharField(max_length=255)),
                ('ID_Camara_Votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.votacao')),
                ('Politico_CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico')),
            ],
        ),
        migrations.CreateModel(
            name='Votacao_Proposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Camara_Proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.proposicao')),
                ('ID_Camara_Votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.votacao')),
            ],
        ),
    ]
