# Generated by Django 5.1.1 on 2024-11-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0003_orgao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='Nome',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
