# Generated by Django 5.1.1 on 2024-11-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0004_partido_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='ID_Camara_Partido',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='Numero_Eleitoral',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='Qty_Membros_Camara',
            field=models.IntegerField(null=True),
        ),
    ]
