# Generated by Django 5.1.1 on 2024-11-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0005_alter_partido_id_camara_partido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='ID_Camara_Partido',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='Numero_Eleitoral',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='Qty_Membros_Camara',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
