# Generated by Django 5.1.1 on 2024-11-10 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0007_alter_partido_lider_partido_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='Lider_Partido_CPF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico'),
        ),
    ]
