# Generated by Django 5.1.1 on 2024-11-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0008_alter_partido_lider_partido_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politico',
            name='Data_Nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Escolaridade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Estado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Estado_Nascimento',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='politico',
            name='ID_Camara_Politico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Municipio_Nascimento',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Partido_Atual',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Profissao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=15),
        ),
    ]
