# Generated by Django 5.1.1 on 2024-11-10 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0009_alter_politico_data_nascimento_alter_politico_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politico',
            name='Telefone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message="O telefone deve ser do seguinte formato: '1234-5678'.", regex='^\\d{4}-\\d{4}$')]),
        ),
    ]
