# Generated by Django 5.1.1 on 2024-11-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0010_alter_politico_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante_partido',
            name='Periodo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='Periodo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
