# Generated by Django 5.1.1 on 2024-11-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0011_alter_integrante_partido_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politico',
            name='Escolaridade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
