# Generated by Django 5.1.1 on 2024-11-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0012_alter_politico_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='CNPJ_Fornecedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='CPF_Politico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='Data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='Fornecedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='PDF_Documento',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='Tipo_Despesa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='Valor_Atual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frente',
            name='CPF_Coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico'),
        ),
        migrations.AlterField(
            model_name='frente',
            name='Nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='frente',
            name='PDF_Frente',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='integrante_partido',
            name='Periodo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='Periodo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='Data_Fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='Data_Inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='ID_Camara_Orgao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='Nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='Sala',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='Website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='Nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Estado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Estado_Nascimento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Municipio_Nascimento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Partido_Atual',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Profissao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='politico',
            name='Sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='Ano_Proposicao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='Data_Situacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='Ementa',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='Keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='Numero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='Sigla_Orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.orgao'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='Situacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='Tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='Data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='Qty_Votos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='Resultado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='Sigla_Orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.orgao'),
        ),
        migrations.AlterField(
            model_name='votacao_politico',
            name='Voto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
