# Generated by Django 5.1.1 on 2024-11-13 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0013_alter_despesa_cnpj_fornecedor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votacao_Politico',
            new_name='Voto_Politico',
        ),
        migrations.RemoveField(
            model_name='integrante_partido',
            name='Periodo',
        ),
        migrations.RemoveField(
            model_name='mandato',
            name='Periodo',
        ),
        migrations.RemoveField(
            model_name='mandato',
            name='Sigla_Partido',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='Numero_Eleitoral',
        ),
        migrations.RemoveField(
            model_name='politico',
            name='Profissao',
        ),
        migrations.AddField(
            model_name='integrante_partido',
            name='Data_Fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrante_partido',
            name='Data_Inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandato',
            name='Estado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mandato',
            name='Fim_Mandato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandato',
            name='Inicio_Mandato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandato',
            name='Legislatura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='Situacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politico',
            name='Nome_Civil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('Data', models.DateField(blank=True, null=True)),
                ('Politico_CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico')),
            ],
        ),
    ]
