# Generated by Django 5.1.1 on 2024-11-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0015_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
