# Generated by Django 5.1.1 on 2024-11-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0017_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='politico',
            name='Foto',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
