# Generated by Django 5.1.1 on 2024-11-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0018_delete_test_alter_politico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='frente',
            name='Legislatura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orgao',
            name='Tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
    ]
