# Generated by Django 5.1.1 on 2024-11-29 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0019_frente_legislatura_orgao_tipo_delete_despesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Despesa', models.CharField(blank=True, max_length=255, null=True)),
                ('PDF_Documento', models.FileField(blank=True, null=True, upload_to='')),
                ('Valor_Atual', models.IntegerField(blank=True, null=True)),
                ('Fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('Data', models.DateField(blank=True, null=True)),
                ('CNPJ_Fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('CPF_Politico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buscandidatoapp.politico')),
            ],
        ),
    ]
