# Generated by Django 5.1.1 on 2024-11-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0020_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante_orgao',
            name='Cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integrante_orgao',
            name='Legislatura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integrante_orgao',
            name='Periodo_Fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrante_orgao',
            name='Periodo_Inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
