# Generated by Django 5.1.1 on 2024-12-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0021_integrante_orgao_cargo_integrante_orgao_legislatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='PDF_Documento',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='Valor_Atual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
