# Generated by Django 5.1.1 on 2024-12-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0022_despesa_codigo_documento_despesa_numero_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='Codigo_Documento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='Numero_Documento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
