# Generated by Django 5.1.1 on 2024-12-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0023_despesa_codigo_documento_despesa_numero_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposicao',
            old_name='Ano_Proposicao',
            new_name='Ano_Apresentacao',
        ),
        migrations.AddField(
            model_name='autor_proposicao',
            name='Nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autor_proposicao',
            name='Tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='Data_Apresentacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='Data_Situacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='Ementa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
