# Generated by Django 5.1.1 on 2024-12-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0024_rename_ano_proposicao_proposicao_ano_apresentacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votacao',
            name='Qty_Votos',
        ),
        migrations.AlterField(
            model_name='votacao',
            name='ID_Camara_Votacao',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
