# Generated by Django 5.1.1 on 2024-12-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscandidatoapp', '0025_remove_votacao_qty_votos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='Logo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
